route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1s
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: 6400828497:AAFlJ_rrNnV2mjt8M_rNh8aSk7WzXUZkwpQ
    api_url: https://api.telegram.org
    chat_id: -1001927109642
    reply_to_message_id: 2



