route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1s
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: <bot_token>
    api_url: https://api.telegram.org
    chat_id: <chat_id>
    reply_to_message_id: <message_id>



