global:
  scrape_interval:     1s 
  evaluation_interval: 1s 

rule_files:
  - alert.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
  - job_name: 'node'
    scrape_interval: 1s
    static_configs:
         - targets:
           - alertmanager:9093

