global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'my-project'


rule_files:
  - alert.rules



alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - localhost:9093


scrape_configs:
  - job_name: 'prometheus'
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
         - targets:
           - localhost:9093

    # relabel_configs:
    #   - source_labels: [__address__]
    #     target_label: __param_target
    #   - source_labels: [__param_target]
    #     target_label: instance
    #   - target_label: __address__
    #     replacement: "localhost:9115" 
    #   - target_label: region
    #     replacement: "local"

